blank_issues_enabled: false
contact_links:
  - name: Report bug
    url: https://bounty.github.com/
    about: Please report security vulnerabilities here.
  - name: Report feature
    url: https://bounty.github.com/
    about: Please report security vulnerabilities here.
  - name: Join to the OPSd community on Slack
    url: https://join.slack.com/t/opsd-community/signup
    about: Please ask and answer questions here.
