name: Bug report
description: File a bug/issue
title: "[BUG]: "
labels: ["bug"]
# assignees:
#   - OPSdiyBot
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Are there other open or closed issues or Pull Requests that match your issue?
    options:
    - label: I have searched the existing issues
      required: true
- type: textarea
  attributes:
    label: Current Behavior
    description: In a few words, describe the problem you are struggling with.
  validations:
    required: false
- type: textarea
  attributes:
    label: Expected Behavior
    description: A concise description of what you expected to happen.
  validations:
    required: false
- type: textarea
  attributes:
    label: Steps To Reproduce
    description: Steps to reproduce the behavior.
    placeholder: |
      1. In this environment...
      2. With this config...
      3. Run '...'
      4. See error...
  validations:
    required: false
- type: textarea
  attributes:
    label: Environment
    description: |
      examples:
        - **Terraform version**: 1.5.5
        - **Terraform provider version**:5.44.0
        - **Terraform module version**: 0.5.1
    value: |
        - Terraform version: X.Y.Z
        - Terraform provider version: X.Y.Z
        - Terraform module version: X.Y.Z
    render: markdown
  validations:
    required: true
- type: textarea
  attributes:
    label: Anything else?
    description: |
      Links? References? Anything that will give us more context about the issue you are encountering!

      **Tip**: You can attach images or log files by clicking this area to highlight it and then dragging files in.
      **Tip**: You can use GitHub Gist to share debug output.
  validations:
    required: false
