blank_issues_enabled: false
contact_links:
  - name: Join to the OPSd community on Slack
    url: https://join.slack.com/t/opsd-community/signup
    about: If you want to contact us personally join our Slack.
