name: Static code analysis

on:
  pull_request:
    # paths-ignore:
    #   - "**.md"
  push:
    # paths-ignore:
    #   - "**.md"

jobs:
  asdf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install all the tools from .tool-versions file
        uses: asdf-vm/actions/install@v1
      - name: verify TF version
        run: terraform --version
